default[:printers][:name]=''
default[:printers][:make]=''
default[:printers][:model]=''
default[:printers][:ppd]=''
default[:printers][:ppd_uri]=''
default[:printers][:uri]=''

default[:multiprinters][:multiprinters][:name]=''
default[:multiprinters][:multiprinters][:make]=''
default[:multiprinters][:multiprinters][:model]=''
default[:multiprinters][:multiprinters][:ppd]=''
default[:multiprinters][:multiprinters][:ppd_uri]=''
default[:multiprinters][:multiprinters][:uri]=''
